// <auto-generated />
using System;
using BattleCats.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BattleCats.DataAccess.Migrations.User
{
    [DbContext(typeof(UserContext))]
    [Migration("20260508190241_AddUserRoleAndSeedUsers")]
    partial class AddUserRoleAndSeedUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BattleCats.Domains.Entities.User.UserData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contacts")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Contacts = "+373 22 000001",
                            DOB = new DateTime(1995, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@catbase.shop",
                            Gender = 0,
                            Password = "de2bbe3336efa2083a96e58558cd2137",
                            Role = 30,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Contacts = "+373 22 000002",
                            DOB = new DateTime(1996, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "manager@catbase.shop",
                            Gender = 0,
                            Password = "b975e0ef031a57d65816b20dab4baca8",
                            Role = 20,
                            UserName = "manager"
                        },
                        new
                        {
                            Id = 3,
                            Contacts = "+373 22 000003",
                            DOB = new DateTime(2000, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user@catbase.shop",
                            Gender = 0,
                            Password = "3bc5f1df7c15c68d62b1afcde8d30918",
                            Role = 1,
                            UserName = "user"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
