// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using BattleCats.DataAccess.Context;

#nullable disable

namespace BattleCats.DataAccess.Migrations.Product
{
    [DbContext(typeof(ProductContext))]
    [Migration("20260423122030_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BattleCats.Domains.Entities.Product.CategoryData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("BattleCats.Domains.Entities.Product.DescriptionAdvanced", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("H")
                        .HasColumnType("int");

                    b.Property<int>("L")
                        .HasColumnType("int");

                    b.Property<int>("W")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DescriptionAdvanced");
                });

            modelBuilder.Entity("BattleCats.Domains.Entities.Product.ProductData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DescriptionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DescriptionId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("BattleCats.Domains.Entities.Product.ProductDescriptionData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DescriptionAdvancedId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DescriptionAdvancedId");

                    b.ToTable("Description");
                });

            modelBuilder.Entity("BattleCats.Domains.Entities.Product.ProductImgData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ProductDataId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductDataId");

                    b.ToTable("ProductImgs");
                });

            modelBuilder.Entity("BattleCats.Domains.Entities.Product.ProductData", b =>
                {
                    b.HasOne("BattleCats.Domains.Entities.Product.CategoryData", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BattleCats.Domains.Entities.Product.ProductDescriptionData", "Description")
                        .WithMany()
                        .HasForeignKey("DescriptionId");

                    b.Navigation("Category");

                    b.Navigation("Description");
                });

            modelBuilder.Entity("BattleCats.Domains.Entities.Product.ProductDescriptionData", b =>
                {
                    b.HasOne("BattleCats.Domains.Entities.Product.DescriptionAdvanced", "DescriptionAdvanced")
                        .WithMany()
                        .HasForeignKey("DescriptionAdvancedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DescriptionAdvanced");
                });

            modelBuilder.Entity("BattleCats.Domains.Entities.Product.ProductImgData", b =>
                {
                    b.HasOne("BattleCats.Domains.Entities.Product.ProductData", null)
                        .WithMany("Images")
                        .HasForeignKey("ProductDataId");
                });

            modelBuilder.Entity("BattleCats.Domains.Entities.Product.ProductData", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
