// <auto-generated />
using System;
using BattleCats.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BattleCats.DataAccess.Migrations.Product
{
    [DbContext(typeof(ProductContext))]
    [Migration("20260509213824_FixSeedImages")]
    partial class FixSeedImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BattleCats.Domains.Entities.Product.BattleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LoreId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PriceEuro")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("LoreId");

                    b.ToTable("BattleItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LoreId = 1,
                            Name = "Cat (Basic Tier)",
                            PriceEuro = 0.99m,
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LoreId = 2,
                            Name = "Tank Cat",
                            PriceEuro = 2.49m,
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LoreId = 3,
                            Name = "Axe Cat",
                            PriceEuro = 3.99m,
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LoreId = 7,
                            Name = "D'artanyan",
                            PriceEuro = 5.99m,
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LoreId = 8,
                            Name = "D'arktanyan",
                            PriceEuro = 9.99m,
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LoreId = 9,
                            Name = "Kaoru Hanayama",
                            PriceEuro = 8.49m,
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LoreId = 10,
                            Name = "Kasli the Bane",
                            PriceEuro = 7.49m,
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LoreId = 11,
                            Name = "King of Doom Phono",
                            PriceEuro = 12.99m,
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LoreId = 12,
                            Name = "Courier Cat",
                            PriceEuro = 3.49m,
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LoreId = 13,
                            Name = "Crazy Baozi Cat",
                            PriceEuro = 1.99m,
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LoreId = 14,
                            Name = "Gamatoto",
                            PriceEuro = 6.99m,
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LoreId = 15,
                            Name = "Legeluga",
                            PriceEuro = 4.49m,
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LoreId = 16,
                            Name = "Pikotaro",
                            PriceEuro = 2.99m,
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LoreId = 17,
                            Name = "Squire Luno",
                            PriceEuro = 5.49m,
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LoreId = 18,
                            Name = "Slime Cat",
                            PriceEuro = 1.49m,
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LoreId = 4,
                            Name = "Worker Cat Speed Up",
                            PriceEuro = 4.99m,
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LoreId = 19,
                            Name = "Breakerblast Base",
                            PriceEuro = 6.99m,
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LoreId = 20,
                            Name = "Default Base",
                            PriceEuro = 0.99m,
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LoreId = 21,
                            Name = "Thunderbolt Base",
                            PriceEuro = 8.99m,
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LoreId = 5,
                            Name = "Attack Power Up Buff",
                            PriceEuro = 1.99m,
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LoreId = 22,
                            Name = "Cat Combo: Pewpewpew!",
                            PriceEuro = 2.49m,
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LoreId = 23,
                            Name = "Cat Combo: Dragon Slayer",
                            PriceEuro = 3.99m,
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LoreId = 6,
                            Name = "Rare Cat Capsule",
                            PriceEuro = 7.99m,
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LoreId = 24,
                            Name = "Gold Gacha Capsule",
                            PriceEuro = 14.99m,
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LoreId = 25,
                            Name = "Normal Gacha Capsule",
                            PriceEuro = 2.99m,
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("BattleCats.Domains.Entities.Product.BattleItemLore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("DescriptionAdvancedId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DescriptionAdvancedId");

                    b.ToTable("Lores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Базовый кот-новобранец. Дешёвый, быстро призывается, отлично прикрывает фронт.",
                            DescriptionAdvancedId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Танкокот с огромным запасом здоровья. Поглощает удары вместо лёгких юнитов.",
                            DescriptionAdvancedId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Снайпер-кот с длинной дальностью атаки. Бьёт врагов из глубокого тыла.",
                            DescriptionAdvancedId = 3
                        },
                        new
                        {
                            Id = 7,
                            Description = "Изящный фехтовальщик в плаще и шляпе. Стремителен и точен, словно D'Artagnan.",
                            DescriptionAdvancedId = 4
                        },
                        new
                        {
                            Id = 8,
                            Description = "Тёмная эволюция D'artanyan'а. Облачён в чёрные доспехи с синим свечением, режет насквозь.",
                            DescriptionAdvancedId = 5
                        },
                        new
                        {
                            Id = 9,
                            Description = "Каору Ханаяма — мастер боевых искусств с разрушительной силой кулака.",
                            DescriptionAdvancedId = 6
                        },
                        new
                        {
                            Id = 10,
                            Description = "Касли — проклятие на двух лапах. Магический урон по площади.",
                            DescriptionAdvancedId = 7
                        },
                        new
                        {
                            Id = 11,
                            Description = "Король Судьбы Phono. Громовая ярость, разрушающая всё на пути.",
                            DescriptionAdvancedId = 8
                        },
                        new
                        {
                            Id = 12,
                            Description = "Бесстрашный курьер. Доставляет посылки прямо на поле боя.",
                            DescriptionAdvancedId = 9
                        },
                        new
                        {
                            Id = 13,
                            Description = "Безумный пельмень-кот. Прыгает на врагов с пугающей радостью.",
                            DescriptionAdvancedId = 10
                        },
                        new
                        {
                            Id = 14,
                            Description = "Гаматото — гигантский исследовательский кот. Откапывает ресурсы.",
                            DescriptionAdvancedId = 11
                        },
                        new
                        {
                            Id = 15,
                            Description = "Легелуга. Фигуристка-кот с ледяной грацией и колкими атаками.",
                            DescriptionAdvancedId = 12
                        },
                        new
                        {
                            Id = 16,
                            Description = "Pen-Pineapple-Apple-Pen Cat. Простая мелодия — мощное оружие.",
                            DescriptionAdvancedId = 13
                        },
                        new
                        {
                            Id = 17,
                            Description = "Сквайр Луно — благородный молодой воин на службе ночи.",
                            DescriptionAdvancedId = 14
                        },
                        new
                        {
                            Id = 18,
                            Description = "Желейный кот. Мягкий снаружи, крепкий внутри. Растворяет врагов кислотой.",
                            DescriptionAdvancedId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Апгрейд скорости работы базы кошачьего штаба. Ускоряет выпуск юнитов."
                        },
                        new
                        {
                            Id = 19,
                            Description = "Breakerblast Base — пушка-разрушитель на крыше базы. Бьёт по дальним целям."
                        },
                        new
                        {
                            Id = 20,
                            Description = "Стандартное укрепление базы. Простое, дешёвое, эффективное против лёгких атак."
                        },
                        new
                        {
                            Id = 21,
                            Description = "Громовая база. Электрическая турель, парализующая врагов на подступах."
                        },
                        new
                        {
                            Id = 5,
                            Description = "Бафф усиленной атаки. Все юниты получают +50% к урону на 30 секунд."
                        },
                        new
                        {
                            Id = 22,
                            Description = "Cat Combo Pewpewpew. Стартовая мощь Cat Cannon усилена. Бьёт чаще и больнее."
                        },
                        new
                        {
                            Id = 23,
                            Description = "Cat Combo Dragon Slayer. Massive Damage против Red, Floating и Angel врагов."
                        },
                        new
                        {
                            Id = 6,
                            Description = "Гача-капсула на редкого юнита. Шанс получить Uber Rare кота."
                        },
                        new
                        {
                            Id = 24,
                            Description = "Золотая капсула. Гарантирует юнита Super Rare или выше."
                        },
                        new
                        {
                            Id = 25,
                            Description = "Обычная капсула. Случайный кот стандартного редкости. Шанс на Rare."
                        });
                });

            modelBuilder.Entity("BattleCats.Domains.Entities.Product.DescriptionAdvanced", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Attack")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<int>("Range")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Stats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Attack = 250,
                            Health = 1500,
                            Range = 140
                        },
                        new
                        {
                            Id = 2,
                            Attack = 600,
                            Health = 4500,
                            Range = 100
                        },
                        new
                        {
                            Id = 3,
                            Attack = 480,
                            Health = 2200,
                            Range = 380
                        },
                        new
                        {
                            Id = 4,
                            Attack = 720,
                            Health = 3200,
                            Range = 290
                        },
                        new
                        {
                            Id = 5,
                            Attack = 1100,
                            Health = 5800,
                            Range = 350
                        },
                        new
                        {
                            Id = 6,
                            Attack = 950,
                            Health = 4100,
                            Range = 270
                        },
                        new
                        {
                            Id = 7,
                            Attack = 880,
                            Health = 3800,
                            Range = 200
                        },
                        new
                        {
                            Id = 8,
                            Attack = 540,
                            Health = 2700,
                            Range = 320
                        },
                        new
                        {
                            Id = 9,
                            Attack = 1500,
                            Health = 9999,
                            Range = 480
                        },
                        new
                        {
                            Id = 10,
                            Attack = 360,
                            Health = 1800,
                            Range = 220
                        },
                        new
                        {
                            Id = 11,
                            Attack = 1300,
                            Health = 6500,
                            Range = 410
                        },
                        new
                        {
                            Id = 12,
                            Attack = 420,
                            Health = 2400,
                            Range = 260
                        },
                        new
                        {
                            Id = 13,
                            Attack = 660,
                            Health = 3300,
                            Range = 240
                        },
                        new
                        {
                            Id = 14,
                            Attack = 280,
                            Health = 1600,
                            Range = 130
                        });
                });

            modelBuilder.Entity("BattleCats.Domains.Entities.Product.ItemCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cat Units"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Base Upgrades"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Buffs"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Gacha"
                        });
                });

            modelBuilder.Entity("BattleCats.Domains.Entities.Product.ProductImgData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BattleItemId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("BattleItemId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BattleItemId = 1,
                            Url = "/images/cats/slime_cat.jpg"
                        },
                        new
                        {
                            Id = 2,
                            BattleItemId = 2,
                            Url = "/images/cats/courier_cat.jpg"
                        },
                        new
                        {
                            Id = 3,
                            BattleItemId = 3,
                            Url = "/images/cats/Kasli_the_Bane.jpg"
                        },
                        new
                        {
                            Id = 7,
                            BattleItemId = 7,
                            Url = "/images/cats/D_artanyan.jpg"
                        },
                        new
                        {
                            Id = 8,
                            BattleItemId = 8,
                            Url = "/images/cats/D_arktanyan.jpg"
                        },
                        new
                        {
                            Id = 9,
                            BattleItemId = 9,
                            Url = "/images/cats/Kaoru_Hanayama.jpg"
                        },
                        new
                        {
                            Id = 10,
                            BattleItemId = 10,
                            Url = "/images/cats/Kasli_the_Bane.jpg"
                        },
                        new
                        {
                            Id = 11,
                            BattleItemId = 11,
                            Url = "/images/cats/King_of_Doom_Phono.jpg"
                        },
                        new
                        {
                            Id = 12,
                            BattleItemId = 12,
                            Url = "/images/cats/courier_cat.jpg"
                        },
                        new
                        {
                            Id = 13,
                            BattleItemId = 13,
                            Url = "/images/cats/crazy_baozi_cat.jpg"
                        },
                        new
                        {
                            Id = 14,
                            BattleItemId = 14,
                            Url = "/images/cats/gamatoto.jpg"
                        },
                        new
                        {
                            Id = 15,
                            BattleItemId = 15,
                            Url = "/images/cats/legeluga.jpg"
                        },
                        new
                        {
                            Id = 16,
                            BattleItemId = 16,
                            Url = "/images/cats/pikotaro.jpg"
                        },
                        new
                        {
                            Id = 17,
                            BattleItemId = 17,
                            Url = "/images/cats/squire_luno.jpg"
                        },
                        new
                        {
                            Id = 18,
                            BattleItemId = 18,
                            Url = "/images/cats/slime_cat.jpg"
                        },
                        new
                        {
                            Id = 4,
                            BattleItemId = 4,
                            Url = "/images/cats/default_base.jpg"
                        },
                        new
                        {
                            Id = 19,
                            BattleItemId = 19,
                            Url = "/images/cats/breakerblast_base.jpg"
                        },
                        new
                        {
                            Id = 20,
                            BattleItemId = 20,
                            Url = "/images/cats/default_base.jpg"
                        },
                        new
                        {
                            Id = 21,
                            BattleItemId = 21,
                            Url = "/images/cats/thunderbolt_base.jpg"
                        },
                        new
                        {
                            Id = 5,
                            BattleItemId = 5,
                            Url = "/images/cats/catcombo_buff_1.jpg"
                        },
                        new
                        {
                            Id = 22,
                            BattleItemId = 22,
                            Url = "/images/cats/catcombo_buff_1.jpg"
                        },
                        new
                        {
                            Id = 23,
                            BattleItemId = 23,
                            Url = "/images/cats/catcombo_buff_2.jpg"
                        },
                        new
                        {
                            Id = 6,
                            BattleItemId = 6,
                            Url = "/images/cats/normal_gacha.jpg"
                        },
                        new
                        {
                            Id = 24,
                            BattleItemId = 24,
                            Url = "/images/cats/gold_gacha.jpg"
                        },
                        new
                        {
                            Id = 25,
                            BattleItemId = 25,
                            Url = "/images/cats/normal_gacha.jpg"
                        });
                });

            modelBuilder.Entity("BattleCats.Domains.Entities.Product.BattleItem", b =>
                {
                    b.HasOne("BattleCats.Domains.Entities.Product.ItemCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BattleCats.Domains.Entities.Product.BattleItemLore", "Lore")
                        .WithMany()
                        .HasForeignKey("LoreId");

                    b.Navigation("Category");

                    b.Navigation("Lore");
                });

            modelBuilder.Entity("BattleCats.Domains.Entities.Product.BattleItemLore", b =>
                {
                    b.HasOne("BattleCats.Domains.Entities.Product.DescriptionAdvanced", "DescriptionAdvanced")
                        .WithMany()
                        .HasForeignKey("DescriptionAdvancedId");

                    b.Navigation("DescriptionAdvanced");
                });

            modelBuilder.Entity("BattleCats.Domains.Entities.Product.ProductImgData", b =>
                {
                    b.HasOne("BattleCats.Domains.Entities.Product.BattleItem", null)
                        .WithMany("Images")
                        .HasForeignKey("BattleItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BattleCats.Domains.Entities.Product.BattleItem", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
