// <auto-generated />
using System;
using BattleCats.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BattleCats.DataAccess.Migrations.Product
{
    [DbContext(typeof(ProductContext))]
    partial class ProductContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BattleCats.Domains.Entities.Product.BattleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LoreId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PriceEuro")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("LoreId");

                    b.ToTable("BattleItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LoreId = 1,
                            Name = "Cat (Basic Tier)",
                            PriceEuro = 0.99m,
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LoreId = 2,
                            Name = "Tank Cat",
                            PriceEuro = 2.49m,
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LoreId = 3,
                            Name = "Axe Cat",
                            PriceEuro = 3.99m,
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LoreId = 4,
                            Name = "Worker Cat Speed Up",
                            PriceEuro = 4.99m,
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LoreId = 5,
                            Name = "Attack Power Up Buff",
                            PriceEuro = 1.99m,
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LoreId = 6,
                            Name = "Rare Cat Capsule",
                            PriceEuro = 7.99m,
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("BattleCats.Domains.Entities.Product.BattleItemLore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("DescriptionAdvancedId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DescriptionAdvancedId");

                    b.ToTable("Lores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Базовый кот-новобранец. Дешёвый, быстро призывается, отлично прикрывает фронт.",
                            DescriptionAdvancedId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Танкокот с огромным запасом здоровья. Поглощает удары вместо лёгких юнитов.",
                            DescriptionAdvancedId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Снайпер-кот с длинной дальностью атаки. Бьёт врагов из глубокого тыла.",
                            DescriptionAdvancedId = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Апгрейд скорости работы базы кошачьего штаба. Ускоряет выпуск юнитов."
                        },
                        new
                        {
                            Id = 5,
                            Description = "Бафф усиленной атаки. Все юниты получают +50% к урону на 30 секунд."
                        },
                        new
                        {
                            Id = 6,
                            Description = "Гача-капсула на редкого юнита. Шанс получить Uber Rare кота."
                        });
                });

            modelBuilder.Entity("BattleCats.Domains.Entities.Product.DescriptionAdvanced", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Attack")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<int>("Range")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Stats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Attack = 250,
                            Health = 1500,
                            Range = 140
                        },
                        new
                        {
                            Id = 2,
                            Attack = 600,
                            Health = 4500,
                            Range = 100
                        },
                        new
                        {
                            Id = 3,
                            Attack = 480,
                            Health = 2200,
                            Range = 380
                        });
                });

            modelBuilder.Entity("BattleCats.Domains.Entities.Product.ItemCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cat Units"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Base Upgrades"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Buffs"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Gacha"
                        });
                });

            modelBuilder.Entity("BattleCats.Domains.Entities.Product.ProductImgData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BattleItemId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("BattleItemId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BattleItemId = 1,
                            Url = "https://battlecats-db.com/img/unit/000/00/icon.png"
                        },
                        new
                        {
                            Id = 2,
                            BattleItemId = 2,
                            Url = "https://battlecats-db.com/img/unit/002/00/icon.png"
                        },
                        new
                        {
                            Id = 3,
                            BattleItemId = 3,
                            Url = "https://battlecats-db.com/img/unit/004/00/icon.png"
                        },
                        new
                        {
                            Id = 4,
                            BattleItemId = 4,
                            Url = "https://battlecats-db.com/img/items/speedup.png"
                        },
                        new
                        {
                            Id = 5,
                            BattleItemId = 5,
                            Url = "https://battlecats-db.com/img/items/buff.png"
                        },
                        new
                        {
                            Id = 6,
                            BattleItemId = 6,
                            Url = "https://battlecats-db.com/img/items/capsule.png"
                        });
                });

            modelBuilder.Entity("BattleCats.Domains.Entities.Product.BattleItem", b =>
                {
                    b.HasOne("BattleCats.Domains.Entities.Product.ItemCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BattleCats.Domains.Entities.Product.BattleItemLore", "Lore")
                        .WithMany()
                        .HasForeignKey("LoreId");

                    b.Navigation("Category");

                    b.Navigation("Lore");
                });

            modelBuilder.Entity("BattleCats.Domains.Entities.Product.BattleItemLore", b =>
                {
                    b.HasOne("BattleCats.Domains.Entities.Product.DescriptionAdvanced", "DescriptionAdvanced")
                        .WithMany()
                        .HasForeignKey("DescriptionAdvancedId");

                    b.Navigation("DescriptionAdvanced");
                });

            modelBuilder.Entity("BattleCats.Domains.Entities.Product.ProductImgData", b =>
                {
                    b.HasOne("BattleCats.Domains.Entities.Product.BattleItem", null)
                        .WithMany("Images")
                        .HasForeignKey("BattleItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BattleCats.Domains.Entities.Product.BattleItem", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
